config/routes.rb
Cookbook::Application.routes.draw do

  get '/admin', to: "admin#dashboard"

  get '/dashboard', to: 'users#show'
  
  get '/login', to: "sessions#new"
  get '/logout', to: "sessions#destroy"

  get '/myrecipe/:id', to: 'users#show_recipe'

  match '/recipes/search', to: 'recipes#search', via: [:get,:post], as: :search_recipes
  match '/ingredients/search', to: 'ingredients#search', via: [:get,:post], as: :search_ingredients

  resources :sessions
  resources :users
  resources :ingredients
  resources :recipes
  
  #--- Static ---#
  root 'static#home'
  get '/about', to: "static#about"
  get '/contact', to:"static#contact"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user ||= User.new
    if @user.role == 'admin'
      can :manage, :all
    else
      binding.pry
      if @user.role == 'user'
        can :manage, :recipes
        can :show, :user
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  belongs_to :food_type
  has_many :ingredients_recipes
  has_many :recipes, through: :ingredients_recipes

  mount_uploader :ingredient_image, IngredientImageUploader
  
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base

  belongs_to :ingredient
  belongs_to :recipe

  validates :ingredient_id, uniqueness: { scope: :recipe_id }
  validates_presence_of :recipe_id, :quantity, :ingredient_id

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :ingredients_recipes
  has_many :ingredients, through: :ingredients_recipes

  mount_uploader :recipe_image, RecipeImageUploader

  accepts_nested_attributes_for :ingredients_recipes, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :recipes
  
  mount_uploader :user_image, UserImageUploader
  
  def role? role
    self.role == role
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  load_and_authorize_resource

  def dashboard
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :search_box
  helper_method :current_user

  rescue_from CanCan::AccessDenied do |excepton|
    redirect_to root_url, alert: 'You cannot access this page'
  end

  def search_box
    @q = Recipe.search(params[:q])
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def authenticate
    unless !current_user
      flash[:error] = "You must be logged in to access this site"
      redirect_to login_url
    end
  end
  
  private

  # def can_access_route
  #   can = Ability.authorized? current_user, params[:controller], params[:action]
  #   unless can
  #     redirect_to "/dashboard/#{current_user.id}"
  #     flash[:notice] = 'You have tried to access a page you are not authorized for'
  #   end
  # end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate, only: [:new, :create, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end
  
  def search
    @q = Recipe.search(params[:q])
    @recipe = @q.result.first
    if !@recipe
      flash[:error] = "No matches for #{params[:q][:name_cont]}"
      redirect_to root_url
    else
      render :show
    end
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    binding.pry
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to '/dashboard' }
      format.json { head :no_content }
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :recipe_image, :directions, :category_id, :user_id, :ingredients_recipes_attributes => [:ingredient_id, :quantity, :id, :_destroy] )
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/users', notice: 'Successfully Logged In'
    else
      redirect_to action: 'new'
      flash[:notice] = 'Invalid Log In Credentials'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @q = Recipe.search(params[:q])
    @recipes = @q.result
    @top_recipe = Recipe.last
  end

  def about
  end

  def contact
  end

  def search
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    authorize! :read, @users
  end
  
  def show
    @user = User.find(current_user.id)
  end

  def show_recipe
    @recipe = Recipe.find(params[:id])
    @user = User.find(current_user.id)
    render action: 'show'
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] ||= @user.id
      flash[:notice] = "Welcome, #{@user.fullname}"
      redirect_to('/dashboard')
    else 
      render('new')
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user].permit(:fullname, :name, :email, :password, :password_confirmation, :user_image))
      redirect_to '/dashboard'
    end
  end

  def destroy
    @user.destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:fullname, :name, :email, :password, :password_confirmation, :user_image)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin?
    current_user.role == 'admin'
  end
  
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def owner?
    @recipe.user_id == current_user.id
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard.html.haml
%h1.center-text= "Admin Dashboard"

.span4.well
  %table.table{style:'width: 17%; margin: auto'}
  %thead
    %th{colspan: 2}
      %h1.center-text Users
  %tr
    %th Name
    %th Username
  - @users.each do |user|
    %tr
      %td= link_to user.fullname, edit_user_path(user)
      %td= user.name
  %tr
    %td{colspan: 2, class:'center-text'}= link_to 'New User', new_user_path, class: 'btn'

app/views/layouts/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.haml
= link_to 'Sous', root_path, class: 'brand'

%ul.nav
  = render 'layouts/search_forms'

%ul.nav.pull-right
  - if current_user
    %li= link_to 'Dashboard', "/dashboard"
    %li= link_to 'My Account', edit_user_path(current_user)
    %li= link_to 'Log Out', logout_path
  - else
    %li= link_to 'Sign Up', new_user_path
    %li= link_to 'Log In', login_path

app/views/layouts/_search_forms.haml
%li
  = search_form_for @q, url: search_recipes_path, html: {method: :post}, class:"navbar-search" do |f|
    = f.text_field :name_cont, placeholder: 'Search Recipes...'
%li
  = search_form_for @q, url: search_ingredients_path, html: {method: :post}, class:"navbar-search" do |f|
    = f.text_field :name_cont, placeholder: 'Search Ingredients...'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Sous"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
    = yield(:head)
  %body
    %script{src: '//tinymce.cachefly.net/4.0/tinymce.min.js'}
    %script tinymce.init({selector: 'textarea'})
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
    = javascript_include_tag "application"