config/routes.rb
Cookbook::Application.routes.draw do

  get '/admin', to: "admin#dashboard"

  get '/dashboard', to: 'users#show'
  
  get '/login', to: "sessions#new"
  get '/logout', to: "sessions#destroy"

  get '/myrecipe/:id', to: 'users#show_recipe'

  match '/recipes/search', to: 'recipes#search', via: [:get,:post], as: :search_recipes
  match '/ingredients/search', to: 'ingredients#search', via: [:get,:post], as: :search_ingredients

  resources :sessions
  resources :users
  resources :ingredients
  resources :recipes
  
  #--- Static ---#
  root 'static#home'
  get '/about', to: "static#about"
  get '/contact', to:"static#contact"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :ingredients_recipes
  has_many :ingredients, through: :ingredients_recipes

  mount_uploader :recipe_image, RecipeImageUploader

  accepts_nested_attributes_for :ingredients_recipes, allow_destroy: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate, only: [:new, :create, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end
  
  def search
    @q = Recipe.search(params[:q])
    @recipe = @q.result.first
    if !@recipe
      flash[:error] = "No matches for #{params[:q][:name_cont]}"
      redirect_to root_url
    else
      render :show
    end
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    binding.pry
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to '/dashboard' }
      format.json { head :no_content }
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :recipe_image, :directions, :category_id, :user_id, :ingredients_recipes_attributes => [:ingredient_id, :quantity, :id, :_destroy] )
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def owner?
    @recipe.user_id == current_user.id
  end
end

app/views/recipes/_fields.haml
= f.fields_for :ingredients_recipes do |ir|
  = ir.label :quantity
  = ir.text_field :quantity

  = ir.collection_select :ingredient_id, Ingredient.all, :id, :name
  = ir.link_to_remove 'Remove!'
= f.link_to_add 'Add!',  :ingredients_recipes

app/views/recipes/_form.html.haml
.row.offset1.form-warnings
  - if @recipe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@recipe.errors.count, "error")} prohibited this recipe from being saved:"
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg

= nested_form_for @recipe do |f|
  .span5.well
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :recipe_image
      = f.file_field :recipe_image
    .field
      = f.label :category
      = f.select 'category_id', Category.all.collect { |c| [c.name,c.id] }
    .field
      = f.label :directions
      = f.text_area :directions
  .span5.well
    .field
      = render 'fields', f: f
    %br
    %br
    .actions.center-text
      = f.submit 'Save', class: 'btn'
      = link_to 'Delete', recipe_path(@recipe), method: :delete, class: 'btn btn-danger'
      = link_to 'Back', recipes_path, class: 'btn'

app/views/recipes/edit.html.haml
%h1.center-text Edit Recipe

= render 'form'

app/views/recipes/index.html.haml
%table.table
  %thead
    %th{colspan:5,style:'text-align:center'}
      %h1.center-text Recipes
  %tr
    %th Name
    %th Category
    %th Pic
    %th User
    %th

  - @recipes.each do |recipe|
    %tr
      %td= link_to recipe.name, recipe
      %td= recipe.category.name
      %td= recipe.recipe_image.url
      %td= recipe.user.name
      %td
        = link_to 'Edit', edit_recipe_path(recipe), class: 'btn'
        = link_to 'Destroy', recipe, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
  %tr
    %td{colspan:5,style:'text-align:center'}= link_to 'New Recipe', new_recipe_path, class: 'btn'

app/views/recipes/new.html.haml
%h1 New recipe

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%h1.center-text= @recipe.name

.span5.well.center-text
  %p.recipe-details
    %h3 Category
    %p= @recipe.category.name.capitalize
  %p
    %h3 Ingredients:
    - @recipe.ingredients_recipes.each do |i|
      %p= "#{i.quantity} #{i.ingredient.name}"
  %p
    %h3 Directions
    %br
    = raw @recipe.directions

.span5.well.center-text

  = image_tag @recipe.recipe_image.detail.url
  %br
  %br
  - if owner? || admin?
    = link_to 'Edit', edit_recipe_path(@recipe), class: 'btn'  
  = link_to 'Back', recipes_path, class: 'btn'