config/routes.rb
Cookbook::Application.routes.draw do

  get '/admin', to: "admin#dashboard"

  get '/dashboard', to: 'users#show'
  
  get '/login', to: "sessions#new"
  get '/logout', to: "sessions#destroy"

  get '/myrecipe/:id', to: 'users#show_recipe'

  match '/recipes/search', to: 'recipes#search', via: [:get,:post], as: :search_recipes
  match '/ingredients/search', to: 'ingredients#search', via: [:get,:post], as: :search_ingredients

  resources :sessions
  resources :users
  resources :ingredients
  resources :recipes
  
  #--- Static ---#
  root 'static#home'
  get '/about', to: "static#about"
  get '/contact', to:"static#contact"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  belongs_to :food_type
  has_many :ingredients_recipes
  has_many :recipes, through: :ingredients_recipes

  mount_uploader :ingredient_image, IngredientImageUploader
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end
  
  def search
    @q = Ingredient.search(params[:q])
    @ingredient = @q.result.first
    render :show
  end
  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ingredient }
      else
        format.html { render action: 'new' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :ingredient_image, :recipe_ids, :food_type_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.haml
= form_for @ingredient do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :food_type
    = f.select 'food_type_id', FoodType.all.collect { |f| [f.name,f.id] }
  .field
    = f.label :ingredient_image
    = f.file_field :ingredient_image
  .actions
    = f.submit 'Save'

app/views/ingredients/edit.html.haml
%h1 Editing ingredient

= render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%table.table{style:'width: 60%; margin: auto'}
  %thead
    %th{colspan: 4}
      %h1.center-text Ingredients
  %tr
    %th Name
    %th Pic
    %th Food Type
    %th

  - @ingredients.each do |ingredient|
    %tr
      %td= link_to ingredient.name, ingredient
      %td= ingredient.ingredient_image.url
      %td= ingredient.food_type.name
      %td
        = link_to 'Edit', edit_ingredient_path(ingredient), class: 'btn'
        = link_to 'Destroy', ingredient, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
  %tr
    %td{colspan: 4, style:'text-align:center'}
      = link_to 'New Ingredient', new_ingredient_path, class: 'btn'

app/views/ingredients/new.html.haml
%h1 New ingredient

= render 'form'

= link_to 'Back', ingredients_path, class: 'btn'

app/views/ingredients/show.html.haml
.span5.well.center-text
  %p
    %h2= @ingredient.name
  %p
    %b Food Type:
    = @ingredient.food_type.name
  %p
    %b Pic:
    %br
    = image_tag @ingredient.ingredient_image.url
.span5.well.center-text
  %h3= "Recipes with #{@ingredient.name}"
  - @ingredient.recipes.each do |r|
    %p= link_to r.name, recipe_path(r)

  = link_to 'Edit', edit_ingredient_path(@ingredient), class: 'btn'
  = link_to 'Back', ingredients_path, class: 'btn'